apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener-traefik-canary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/f-lab-edu/Url-Shortener-EKS-Platform
    targetRevision: cvt/traefik
    path: url-shortener/k8s/traefik-canary
  destination:
    server: https://kubernetes.default.svc
    namespace: url-shortener
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
