{{- if .Values.ingress.enabled }} # values.yaml에서 ingress.enabled가 true일 때만 이 리소스를 생성
                                  # dev 환경에서 Ingress 없이 port-forward로 테스트하는 경우에 좋음
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  {{- with .Values.ingress.annotations }} # values.yaml에 값이 존재한다면 아래를 실행
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    {{- if .Values.ingress.host }} # ALB DNS를 사용하는 경우 아래 hosts는 필요 없으니 생략하도록 구현함
    - host: {{ .Values.ingress.host | quote }} # 특정 도메인으로 들어오는 요청만 처리
      http:
        paths:
          - path: /
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Release.Name }}-svc
                port:
                  number: 80
    {{- else }}
    - http:
        paths:
          - path: /
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Release.Name }}-svc
                port:
                  number: 80
    {{- end }}
{{- end }}
