apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: url-shortener-traefik-cert
  namespace: url-shortener
spec:
  secretName: url-shortener-traefik-tls
  issuerRef:
    name: letsencrypt-traefik
    kind: ClusterIssuer
  dnsNames:
    - traefik-api.bidflow.cloud
