apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 41.0.2
    helm:
      values: |
        deployment:
          replicas: 2

        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi

        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        ingressClass:
          enabled: true
          isDefaultClass: false # true 로 설정하면 traefik-ingress-controller 가 ingressClassName 을 쓰지 않은 Ingress 도 처리할 수 있음
          name: traefik

        # 라우팅 설정을 어디서 읽어 올지 결정하는 설정
        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik
          kubernetesIngress:
            enabled: true
            ingressClass: traefik
            publishedService:
              enabled: true

        service:
          enabled: true
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "external"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          spec:
            type: LoadBalancer

        ports:
          web:
            exposedPort: 80
            http:
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https
                  permanent: true
          websecure:
            exposedPort: 443

        log:
          level: INFO
        accessLog:
          enabled: true

        metrics:
          prometheus:
            addEntryPointsLabels: true
            addRoutersLabels: true
            addServicesLabels: true
            buckets: "0.01,0.025,0.05,0.1,0.25,0.5,1.0,2.0,5.0"
            service:
              enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
