apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 41.0.2
    helm:
      values: |
        deployment:
          replicas: 2

        ingressClass:
          enabled: true
          isDefaultClass: false # true 로 설정하면 traefik-ingress-controller 가 ingressClassName 을 쓰지 않은 Ingress 도 처리할 수 있음
          name: traefik

        # 라우팅 설정을 어디서 읽어 올지 결정하는 설정
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
            ingressesClassName: traefik
            publishedService:
              enabled: true

          services:
            enabled: true
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "external"
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          
          ports:
            web:
              port: 80
            websecure:
              port: 443

            logs:
              general:
                level: INFO
              access:
                enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true