apiVersion: v2
name: url-shortener-chart
description: URL Shortener EKS Platform Helm Chart
type: application
version: 0.1.0        # Chart 자체의 버전 (Chart 구조가 바뀔 때 올림)
appVersion: '1.0.0'   # 배포하는 앱의 버전 (Docker 이미지 태그와 맞추는 것 권장)
