api:
  replicas: 2           # prod는 고가용성을 위해 2개
  image:
    repository: 716174522908.dkr.ecr.ap-northeast-2.amazonaws.com/url-shortener
    tag: sha-39eed71
    pullPolicy: IfNotPresent
  env:
    appEnv: production
    debug: 'false'      # prod는 디버그 비활성화

postgres:
  database: urldb
  # 민감정보는 values.prod-secret.yaml로 분리해서 사용하세요 (Git ignore 권장)
  password: ""
  databaseUrl: ""
  storage: 10Gi         # prod는 스토리지 넉넉하게
  storageClass: gp2

ingress:
  enabled: false
