apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter    # OCI 레지스트리
    chart: karpenter
    targetRevision: 1.1.1
    helm:
      values: |
        settings:
          clusterName: urlshortener
          interruptionQueue: Karpenter-urlshortener
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::716174522908:role/KarpenterController-20260410025633575600000018
        controller:
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
